image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Workspace
    init: |
      npm install -g pnpm
      pnpm install
    command: |
      cd packages/bunnyera-console-electron
      pnpm run dev

ports:
  - port: 5173
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - bradlc.vscode-tailwindcss
    - ms-vscode.vscode-typescript-next
