packages:
  # Core packages
  - 'packages/bunnyera-console-core'
  - 'packages/bunnyera-console-ui'
  - 'packages/bunnyera-console-apps'
  - 'packages/bunnyera-console-electron'
  
  # Documentation (if needed)
  - 'docs'
  
  # Tools and utilities (if needed)
  - 'tools/*'

# Catalog configuration for better dependency management
catalog:
  # React ecosystem
  react: ^18.2.0
  react-dom: ^18.2.0
  '@types/react': ^18.2.0
  '@types/react-dom': ^18.2.0
  
  # TypeScript
  typescript: ^5.3.0
  '@types/node': ^20.10.0
  
  # Build tools
  vite: ^5.0.0
  '@vitejs/plugin-react': ^4.2.0
  
  # Electron
  electron: ^28.0.0
  electron-builder: ^24.8.0
  electron-updater: ^6.1.0
  
  # UI libraries
  '@headlessui/react': ^1.7.0
  '@heroicons/react': ^2.0.0
  'tailwindcss': ^3.3.0
  '@tailwindcss/forms': ^0.5.0
  '@tailwindcss/typography': ^0.5.0
  'autoprefixer': ^10.4.0
  'postcss': ^8.4.0
  
  # State management
  zustand: ^4.4.0
  '@tanstack/react-query': ^5.0.0
  
  # Routing
  'react-router-dom': ^6.20.0
  
  # Forms
  'react-hook-form': ^7.48.0
  '@hookform/resolvers': ^3.3.0
  zod: ^3.22.0
  
  # Utilities
  clsx: ^2.0.0
  'date-fns': ^2.30.0
  'framer-motion': ^10.16.0
  
  # Development tools
  eslint: ^8.54.0
  prettier: ^3.1.0
  vitest: ^1.0.0
  '@playwright/test': ^1.40.0

# Shared configuration
shared:
  # Node.js version requirement
  engines:
    node: '>=18.0.0'
    pnpm: '>=8.0.0'
  
  # Common dev dependencies that should be hoisted
  devDependencies:
    - typescript
    - '@types/node'
    - eslint
    - prettier
    - vitest

# Publishing configuration
publishConfig:
  registry: 'https://registry.npmjs.org/'
  access: 'public'

# Dependency resolution rules
resolutions:
  # Ensure consistent React versions
  'react': 'catalog:react'
  'react-dom': 'catalog:react-dom'
  '@types/react': 'catalog:@types/react'
  '@types/react-dom': 'catalog:@types/react-dom'
  
  # Security fixes
  'semver': '>=7.5.2'
  'word-wrap': '>=1.2.4'